---
resolver: lts-20.26
arch: x86_64
packages: ["."]
allow-newer: true
extra-deps:
  - aeson-2.0.3.0
  - bytestring-0.11.4.0
  - http-client-0.7.13.1
  - http-client-tls-0.3.6.1
  - hspec-2.9.7
  - text-1.2.5.0
