---
resolver: lts-19.27
arch: x86_64
packages: ["."]
allow-newer: true
extra-deps:
  - aeson-2.0.3.0
  - bytestring-0.10.12.1
  - http-client-0.7.13.1
  - http-client-tls-0.3.6.1
  - hspec-2.8.5
  - text-1.2.5.0
